branch: master  # Specify the branch to be used for deployment

services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: uvicorn index:app --host 0.0.0.0 --port 10000
